### PR TITLE
secrethitler.online is down

### PR DESCRIPTION
**Pull request by alex-grover**
No option to open issues on this repo!

### CODE REVIEW

**Comment by PDarrall** [comment]
Working on getting a version live at secrethitler.games

**Comment by ethanlee16** [comment]
Live version at https://sechit.herokuapp.com; it's a free Heroku instance so if you want to add a domain to point to it, let me know 😄

**Comment by queuebit** [comment]
@ethanlee16 Any chance you documented the deployment process in case that goes down too?

**Comment by ghost** [comment]
ethanlee16 how did you set it up? I get a blank page with the title "secret hitler" and the correct favicon when opening /public/index.html

**Comment by alex-grover** [comment]
@Stuuupiiid it's a web app, so you need to run the server. `node server.js` will make it available at `localhost:8004`. You may need to have postgres running and set `$DATABASE_URL` to get the game to play, I haven't tested it

**Comment by alex-grover** [comment]
should be really easy to deploy to heroku, especially since there's no build process (and he included the dependencies here?)

**Pull request closed without merging**
